//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeritecAssignment.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeritecAssignment.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating salary details....
        /// </summary>
        internal static string CalculatingSalaryDetails {
            get {
                return ResourceManager.GetString("CalculatingSalaryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $#,##0.00;-$#,##0.00;$0.
        /// </summary>
        internal static string CurrencyFormat {
            get {
                return ResourceManager.GetString("CurrencyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductions:.
        /// </summary>
        internal static string Deductions {
            get {
                return ResourceManager.GetString("Deductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your pay frequency (W for weekly, F for fortnightly, M for monthly):.
        /// </summary>
        internal static string EnterPayFrequency {
            get {
                return ResourceManager.GetString("EnterPayFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your salary package amount:.
        /// </summary>
        internal static string EnterYourSalaryAmount {
            get {
                return ResourceManager.GetString("EnterYourSalaryAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid currency.
        /// </summary>
        internal static string Error_NotAValidCurrency {
            get {
                return ResourceManager.GetString("Error_NotAValidCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option you entered is not valid.
        /// </summary>
        internal static string Error_NotAValidSelection {
            get {
                return ResourceManager.GetString("Error_NotAValidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value entered is out of range.
        /// </summary>
        internal static string Error_ValueNotInRange {
            get {
                return ResourceManager.GetString("Error_ValueNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string FORTNIGHT {
            get {
                return ResourceManager.GetString("FORTNIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fortnight.
        /// </summary>
        internal static string FortnightForDisplay {
            get {
                return ResourceManager.GetString("FortnightForDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross package:.
        /// </summary>
        internal static string GrossPackage {
            get {
                return ResourceManager.GetString("GrossPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string MONTH {
            get {
                return ResourceManager.GetString("MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string MonthForDisplay {
            get {
                return ResourceManager.GetString("MonthForDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net income:.
        /// </summary>
        internal static string NetIncome {
            get {
                return ResourceManager.GetString("NetIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay packet:.
        /// </summary>
        internal static string PayPacket {
            get {
                return ResourceManager.GetString("PayPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per.
        /// </summary>
        internal static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to end....
        /// </summary>
        internal static string PressAnyKeyToEnd {
            get {
                return ResourceManager.GetString("PressAnyKeyToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable income:.
        /// </summary>
        internal static string TaxableIncome {
            get {
                return ResourceManager.GetString("TaxableIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string WEEK {
            get {
                return ResourceManager.GetString("WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        internal static string WeekForDisplay {
            get {
                return ResourceManager.GetString("WeekForDisplay", resourceCulture);
            }
        }
    }
}
